name: CI - Testes Automatizados

on:
  schedule:
    - cron: '0 8 * * 1-5'   # Executa às 08:00h de segunda a sexta
  pull_request:
    branches:
      - main
  workflow_dispatch:        # Permite executar manualmente no GitHub

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    # Matriz de parâmetros: tag e browser
    strategy:
      matrix:
        tag: [regression, smoke]    # Tags de cenário que usar
        browser: [chrome, firefox]  # Browsers suportados

    env:
      CYPRESS_BROWSER: ${{ matrix.browser }}
      TEST_TAG: ${{ matrix.tag }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes com Cypress
        run: |
          npx cypress run --browser $CYPRESS_BROWSER --env grepTags=$TEST_TAG

      - name: Upload relatório mochawesome
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report-${{ matrix.tag }}-${{ matrix.browser }}
          path: cypress/reports

      - name: Publicar relatório no GitHub Pages
        if: github.ref == 'refs/heads/main' && success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports
